image:
- Visual Studio 2017
# - Visual Studio 2019

environment:
    # The package name
    PACKAGE: "mydevoirs"
    SUBLIME_TEXT_VERSION : "3"
    KIVY_GL_BACKEND: angle_sdl2

install:
    - "SET PYTHON=C:\\Python37"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - python --version
    - appveyor DownloadFile "https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py"
    - python get-poetry.py -y
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
    - "SET PATH=%USERPROFILE%\\.poetry\\bin;%PATH%"
    - poetry run python -m pip install -U pip
    - poetry run python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.1.22 kivy_deps.glew==0.1.12 kivy_deps.gstreamer==0.1.17 kivy_deps.angle==0.1.9 pywin32-ctypes pefile 
    - poetry install


build: off

test_script:

    - poetry -V
    - poetry run pytest


after_test:
    - poetry run  pyinstaller -y --clean main_win.spec

artifacts:
    - path: dist/MyDevoirs.exe

deploy:
    provider: GitHub
    description: ""
    auth_token:
        secure: e5aQJKglxrA/1tR6pEh5U7CTTcyGNTQSc65k7yeOilgl6JNOFqPqSSWvgeu3qz5H
    on:
        branch: master
        APPVEYOR_REPO_TAG: true
