[tool.poetry]
name = "mydevoirs"
version = "0.1.0"
description = ""
authors = ["jgirardet <ijkl@netc.fr>"]

[tool.poetry.dependencies]
python = "^3.6"
pony = "^0.7.11"
appdirs = "^1.4.3"
kivy = "^1.11.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
black = {version = "*", allows-prereleases = true}
coverage = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
