[tool.briefcase]
project_name = "mydevoirs"
bundle = "coding.cacahuete"
version = "0.6.4"
url = "https://jgirardet.github.io/mydevoirs"
license = "GNU General Public License v3 (GPLv3)"
author = 'Jimmy Girardet'
author_email = "ijkl@netc.fr"

[tool.briefcase.app.mydevoirs]
formal_name = "mydevoirs"
description = "La prise de devoirs enfin simple !"
icon = "mydevoirs/data/icons/logo"
sources = ['mydevoirs']
requires = ['kivy==2.0.0rc3',
            'pony>=0.7.11,<0.8',
            'appdirs>=1.4,<1.5',
            'kivy-garden.filebrowser==1.1.2']


[tool.briefcase.app.mydevoirs.macOS]
requires = []

[tool.briefcase.app.mydevoirs.linux]
requires = []
system_requires = ["xclip"]

[tool.briefcase.app.mydevoirs.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.mydevoirs.iOS]
requires = []

[tool.briefcase.app.mydevoirs.android]
requires = []

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88


