name: Windows Unittests

on: [push, pull_request]

env:
  USE_SDL2: 1
  USE_GSTREAMER: 1
  GST_REGISTRY: '~/registry.bin'
  KIVY_GL_BACKEND: 'angle_sdl2'
  KIVY_SPLIT_EXAMPLES: 1
  CODECOV_TOKEN: b12c1d6f-032c-40bf-ab16-3cc301e48115
  POETRY_PATH: ${ echo $USERPROFILE}\.poetry\bin\poetry
  POETRY_PATHH: ${ echo %USERPROFILE%}\.poetry\bin\poetry
  POETRY_PATHHH: "$USERPROFILE\\.poetry\\bin\\poetry"
  POETRY_PATHHHH: "%USERPROFILE%\\.poetry\\bin\\poetry"


jobs:
  unit_test:
    runs-on: windows-latest
      # PATH: ${{env.path}};\.poetry\bin
    # strategy:
    #   matrix:
    #     python: [3.7']
    #     # python: [3.7', '3.8' ]
        # arch: ['x64', 'x86']
    steps:
    - name: get repo
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      # with:
      with:
        python-version: 3.7
      #   python-version: ${{ matrix.python }}
      #   architecture: ${{ matrix.arch }}
    - name: Install poetry
      env:
        runner: ${{toJson(runner)}}
      run: |
        echo ${runner}
        python -m pip install poetry
    - name: Install Windows dependencies
      if : runner.os == 'Windows'
      run: |
        poetry run python -m pip install  docutils pygments pypiwin32 kivy_deps.sdl2==0.1.22 kivy_deps.glew==0.1.12 kivy_deps.gstreamer==0.1.17 kivy_deps.angle==0.1.9 pywin32-ctypes pefile
    - name: Install common dependencies
      run: poetry install
    - name: test mydevrois
      run: |
        poetry run python -m pytest
    - name: cov
      run: |
        $ENV:PATH="$ENV:PATH;$ENV:USERPROFILE\.poetry\bin"
        poetry run coverage run --rcfile=.coveragerc_win -m pytest
        poetry run coverage report
    - name: build
      run: |
        $ENV:PATH="$ENV:PATH;$ENV:USERPROFILE\.poetry\bin"
        poetry run  python scripted/build_executable.py